Repository kubevirt/bridge-marker, pull requests merged in 2021-08, with the labels that each got.

#38 Pass cache as pointer
  cluster/sync.sh
  cmd/marker/main.go
  pkg/marker/marker.go
  tests/marker_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#37 Set max unavailable to 10%
  manifests/bridge-marker.yml.in
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#41 cluster-sync: pull image from registry
  cluster/sync.sh
Labels: release-note-none, size/XS, dco-signoff: yes, approved

#43 tests, marker-test: increase timeout
  tests/marker_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
